### Copied verbatim from Big Bang customer template:
### https://repo1.dso.mil/big-bang/customers/template/-/blob/main/gitRepo/dev/kustomization.yaml?ref_type=heads
### Presented here only for ease of reading in context with other files. No additional documentation added.

configMapGenerator:
- behavior: merge
  files:
  - values.yaml=configmap.yaml
  name: environment

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- secrets/dev-bb-secret.enc.yaml
patches:
# # Enable the line below if a secrets.enc.yaml is created in this directory
# - path: secrets.enc.yaml
- patch: |-
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: bigbang
    spec:
      interval: 1m
  # Use the following three lines to test a new version of Big Bang without affecting other environments
  #   ref:
  #     $patch: replace
  #     tag: "3.7.0"
- patch: |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: bigbang
    spec:
      interval: 1m
      valuesFrom:
        - kind: Secret
          name: common-bb
        - kind: ConfigMap
          name: common
        - kind: ConfigMap
          name: environment
        - kind: Secret
          name: dev-bb-secret
